### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by tbhal** [cryptomanic/Railway-Management-System#1]
while running the code it's showing that "no data source are configured to run this SQL and provide code assistance".
Please tell do i have to create a new data source for it.

**Comment by cryptomanic** [comment]
1) Open ubuntu command prompt
2) Start mysql as `mysql -u <your_user> -p`
3) Create database `railway_management` as `create database railway_management;`
4) Select database as `use railway_management;`
5) Use `commands.sql` file in the main repository to create and populate tables. 
Run `source <path>/Railway-Management-System/commands.sql`
6) Now run `python manage.py runserver`

**Comment by tbhal** [comment]
Thank you for posting.
I did that.
The problem is in my laptop's mysql server it gives error 2002.
I used other machine and it worked thank you
